// Generated by CoffeeScript 1.6.3
(function() {
  var fs, lm, qrAuth;

  fs = require('fs');

  lm = require('src/login-manager.coffee');

  qrAuth = function(options) {
    var exclude, maxAge;
    exclude = options.exclude, maxAge = options.maxAge;
    return function(req, res, next) {
      var sid;
      sid = req.sessionID;
      if (lm.test(sid)) {
        return next();
      } else {
        return lm.login(sid, maxAge);
      }
    };
  };

  module.exports = qrAuth;

}).call(this);
