// Generated by CoffeeScript 1.6.3
(function() {
  var fs, isLogin, loggedIn, login, qrAuth;

  fs = require('fs');

  loggedIn = [];

  login = function(sid, maxAge) {
    var now, sess;
    now = (new Date()).getTime();
    sess = {
      sid: sid,
      expires: now + maxAge
    };
    return loggedIn.push(sess);
  };

  isLogin = function(sid) {
    var matches;
    loggedIn = loggedIn.filter(function(elem) {
      return elem.expires > now;
    });
    matches = loggedIn.filter(function(elem) {
      return elem.sid === sid;
    });
    return matches.length > 0;
  };

  qrAuth = function(options) {
    var exclude, maxAge;
    exclude = options.exclude, maxAge = options.maxAge;
    return function(req, res, next) {
      var sid;
      sid = req.sessionID;
      if (isLogin(sid)) {
        return next();
      } else {
        return login(sid, maxAge);
      }
    };
  };

  module.exports = qrAuth;

}).call(this);
