// Generated by CoffeeScript 1.6.3
(function() {
  var apiHandle, fs, lm, yaqrcode;

  fs = require('fs');

  lm = require('./login-manager.js');

  apiHandle = require('./auth-api.js');

  yaqrcode = require('yaqrcode');

  module.exports = function(options) {
    var exclude, keygen, maxAge;
    exclude = options.exclude, maxAge = options.maxAge, keygen = options.keygen;
    return function(req, res, next) {
      var sid;
      if ((exclude != null) && exclude.indexOf(req.url) > -1) {
        next();
      }
      if (req.method === 'POST') {
        return apiHandle(req, res, keygen);
      } else {
        sid = req.sessionID;
        if (lm.test(sid)) {
          return next();
        } else {
          res.writeHead(200, {
            'Content-Type': 'text/html'
          });
          return fs.readFile("template.html", {
            encoding: 'UTF-8'
          }, function(err, html) {
            var json;
            json = {
              sid: sid,
              remote: req.protocol + "://" + req.get('host') + req.url
            };
            json = JSON.stringify(json);
            html = html.replace(new RegExp('{{qrcode}}', 'g'), yaqrcode(json));
            res.write(html);
            return res.end();
          });
        }
      }
    };
  };

}).call(this);
