// Generated by CoffeeScript 1.6.3
(function() {
  var apiHandle, fs, lm, yaqrcode;

  fs = require('fs');

  lm = require('./login-manager.js');

  apiHandle = require('./auth-api.js');

  yaqrcode = require('yaqrcode');

  module.exports = function(options) {
    var exclude, keygen, maxAge, template;
    exclude = options.exclude, maxAge = options.maxAge, keygen = options.keygen, template = options.template;
    if (template == null) {
      template = fs.readFileSync("../template.html", {
        encoding: 'UTF-8'
      });
    }
    return function(req, res, next) {
      var json, protocol, sid;
      if ((exclude != null) && exclude.indexOf(req.url) > -1) {
        next();
      }
      if (req.method === 'POST') {
        return apiHandle(req, res, keygen);
      } else {
        sid = req.sessionID;
        if (lm.test(sid)) {
          return next();
        } else {
          res.writeHead(200, {
            'Content-Type': 'text/html'
          });
          if (req.headers["X-Forwarded-Protocol"] && req.headers["X-Forwarded-Protocol"] === 'https') {
            protocol = 'https';
          } else {
            protocol = 'http';
          }
          json = {
            sid: sid,
            remote: protocol + "://" + req.headers.host + req.url
          };
          json = JSON.stringify(json);
          res.write(template.replace(new RegExp('{{qrcode}}', 'g'), yaqrcode(json)));
          return res.end();
        }
      }
    };
  };

}).call(this);
