// Generated by CoffeeScript 1.6.3
(function() {
  var yaqrcode;

  yaqrcode = require('yaqrcode');

  module.exports = function(options) {
    options.key = (new Buffer(options.key)).toString('hex');
    return yaqrcode(JSON.stringify(options));
  };

}).call(this);
